### PR TITLE
Update/bsm visualizer

### PR DESCRIPTION
**Pull request by mwodahl**
# PR Details

Updates the BSM/PSM visualizer to remove previous BigQuery limitations

## Description

This PR trims the slider start/end date when data is returned to the first / last record present. Additionally, the BSM/PSM visualizer notifies the user if no records were returned. The API has been updated to filter returned records to only include the nth record in the case that the mongodb query results in a large dataset. 

## How Has This Been Tested?

This has been tested locally while using port-forward to target the dev MongoDB. 

## Types of changes

- [ X ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ X ] My changes require new environment variables:
  - [ X ] I have updated the docker-compose, K8s YAML, and all dependent deployment configuration files.
- [ X ] My changes require updates to the documentation:
  - [ X ] I have updated the documentation accordingly.
- [ ] My changes require updates and/or additions to the unit tests:
  - [ ] I have modified/added tests to cover my changes.
- [ X ] All existing tests pass.

### CODE REVIEW

**Comment by drewjj** [comment]
Looks like the tests are not passing based on the automated checks

**Comment by payneBrandon** [comment]
> Looks like the tests are not passing based on the automated checks

@drewjj this seems to be resolved

**Review by Michael7371 — APPROVED** [review]
Looks good!

**Review by drewjj — APPROVED** [review]
This appears to still be functional after all of the other branches have merged so that's good. All the services and webapp tests pass. I think this is a reasonable solution since mongo I don't believe maintains the entire filter response in memory. I believe it steps through it.

I do see that an environment variable was added. Please make a devops pr to include this in the helm yaml. It would probably be good to update the one in this repository with the environment variable too.

**Comment by mwodahl** [comment]
Updated the example K8s yaml file for the cv-manager api and opened a devops PR to include the new environment variable in the cv-manager-api yaml file.

**Review by drewjj — APPROVED** [review]
Awesome, got your devops pr merged so we are good here!

**Pull request merged**
