### PR TITLE
Adding CI/CD Support

### PR DESCRIPTION
**Pull request by drewjj**
Added CI/CD for Azure Pipelines support in CDOT DevOps. These are generic pipelines that can be used by all users of the repository and doesn't have any specific configurations for CDOT in them.

These pipelines are fully functional in the CDOT fork of this repository and will push images to the CDOT dev deployment environments when this merges and for every merge into develop going forward that involves changes in each pipeline's specified directory.

### CODE REVIEW

**Review by Michael7371 — APPROVED** [review]
Looks good!

**Review by Michael7371 — APPROVED** [review]
Looks good!

**Review by dmccoystephenson — APPROVED** [review]
Looks good to me! Will this work on USDOT's repository as well?

**Comment by drewjj** [comment]
> Looks good to me! Will this work on USDOT's repository as well?

It would if someone were to have permissions for the USDOT repository and hooked their release pipeline up to the repository. Ideally users would just do this on their own forks if they want to integrate CICD into their deployments.

**Review by mwodahl — APPROVED** [review]

**Review by payneBrandon — APPROVED** [review]
lgtm!

**Pull request merged**
