### PR TITLE
WCAG Status Messages

### PR DESCRIPTION
**Pull request by mwodahl**
Updates all existing status and error messages to include the correct 'role' value. 

Additionally, updates all testing snapshots that were affected by these changes. All existing unit tests have been verified to pass

### CODE REVIEW

**Review by dmccoystephenson — APPROVED** [review]
The code looks good & the webapp unit tests are passing!

**Review by payneBrandon — APPROVED** [review]
lgtm!

**Review by drewjj — CHANGES_REQUESTED** [review]
There are conflicts

**Review by drewjj — APPROVED** [review]
Looks good

**Pull request merged**
