### PR TITLE
Add encryption PW for NTCIP1218 SNMP Operations

### PR DESCRIPTION
**Pull request by mwodahl**
Adds an encrypt_password field to the snmp_credentials table. As SNMP version 3 allows for different authentication and encryption password values this change is necessary. This field is not required and will default to the value of the 'password' field in the case that the value is null. This change has been tested locally and unit tests have been updated to pass.

### CODE REVIEW

**Comment by payneBrandon** [comment]
@mwodahl looks like some merge conflicts we need to handle before we can merge in

**Review by payneBrandon — CHANGES_REQUESTED** [review]
Just the merge conflicts, otherwise looking good

**Review by drewjj — CHANGES_REQUESTED** [review]
We should also just write a small change script that we can run to modify existing snmp_credentials tables to add the new column. This will allow us a smoother deployment across existing deployments.

https://github.com/CDOT-CV/jpo-cvmanager/tree/Update/add-encrypt-pw/resources/sql_scripts/update_scripts

**Comment by mwodahl** [comment]
Fixed merge conflicts, added an update script for the existing snmp_credentials table

**Review by payneBrandon — APPROVED** [review]

**Review by dmccoystephenson — APPROVED** [review]
Looks good to me!

**Review by drewjj — APPROVED** [review]
Looks good

**Pull request merged**
