### PR TITLE
Add Material UI Dialogs

### PR DESCRIPTION
**Pull request by mwodahl**
# PR Details

This PR updates the admin and contact support menus to use Material UI Dialogs instead of sub-pages for add and edit functionality. 

## How Has This Been Tested?

This has been tested locally using docker-compose. Unit tests for the webapp were verified to work using npm.

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ X ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] My changes require new environment variables:
  - [ ] I have updated the docker-compose, K8s YAML, and all dependent deployment configuration files.
- [ ] My changes require updates to the documentation:
  - [ ] I have updated the documentation accordingly.
- [ X ] My changes require updates and/or additions to the unit tests:
  - [ X ] I have modified/added tests to cover my changes.
- [ X ] All existing tests pass.

### CODE REVIEW

**Review by drewjj — CHANGES_REQUESTED** [review]
The changes look good! I am seeing 2 webapp test failures, however. One with src/components/AdminOrganizationDeleteMenu.test.tsx and another with src/components/AdminTable.test.tsx.

**Review by dmccoystephenson — CHANGES_REQUESTED** [review]
These changes look good, but I am seeing some failing unit tests:

image

**Review by drewjj — APPROVED** [review]
Tests are working now

**Comment by drewjj** [comment]
> These changes look good, but I am seeing some failing unit tests:
> 
> image

@dmccoystephenson Mind checking if the tests work for you now?

**Comment by drewjj** [comment]
I resolved the merge conflicts and update the add/edit page headers to not display so the dialog box doesn't look out of place

**Review by payneBrandon — APPROVED** [review]
lgtm!

**Pull request merged**
