### PR TITLE
Aborting Intersection Requests When Leaving the intersectionMap page

### PR DESCRIPTION
**Pull request by jacob6838**
# PR Details

## Description

This PR enables the cancelling of long intersection requests when navigating away from the intersectionMap page. This utilizes the "cleanup" response option of a useEffect to only trigger when the map-component leaves the render tree. 

The method for cancelling all requests is to first cancel all active abort controllers, and then set the new flag "abortAllFutureRequests", which stops chained requests from being spun off from the intersectionMap/pullInitialData thunk

## How Has This Been Tested?

This was tested locally, by continually switching to and from the intersectionMap page with intersection 12109 selected. By varying the timing, i was able to confirm that each of the requests, and subsequent chained requests are cancelled as expected.

## Types of changes

- [x] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] My changes require new environment variables:
  - [ ] I have updated the docker-compose, K8s YAML, and all dependent deployment configuration files.
- [ ] My changes require updates to the documentation:
  - [ ] I have updated the documentation accordingly.
- [ ] My changes require updates and/or additions to the unit tests:
  - [ ] I have modified/added tests to cover my changes.
- [x] All existing tests pass.

### CODE REVIEW

**Review by drewjj — APPROVED** [review]
Tests pass and looks good!

**Review by payneBrandon — CHANGES_REQUESTED** [review]
Looks good, but do we want to add in some unit tests to cover changes? Actually it looks like we don't have any unit tests for most or all of the intersection side of things. Did you want to tackle all the tests at once in another PR or add in some tests to cover these changes now?

**Comment by jacob6838** [comment]
> Looks good, but do we want to add in some unit tests to cover changes? Actually it looks like we don't have any unit tests for most or all of the intersection side of things. Did you want to tackle all the tests at once in another PR or add in some tests to cover these changes now?

The tests for the intersection components are going to be quite substantial... even for some of the smaller tests, there is a lot of setup to mock the state stores, which will be mostly shared between the tests. I would rather tackle these in large groups (probably not al at once, but certainly batched)

**Comment by payneBrandon** [comment]
> > Looks good, but do we want to add in some unit tests to cover changes? Actually it looks like we don't have any unit tests for most or all of the intersection side of things. Did you want to tackle all the tests at once in another PR or add in some tests to cover these changes now?
> 
> The tests for the intersection components are going to be quite substantial... even for some of the smaller tests, there is a lot of setup to mock the state stores, which will be mostly shared between the tests. I would rather tackle these in large groups (probably not al at once, but certainly batched)

So for now we're ok with the changed code not having any tests and pushing that to a backlog item?

**Comment by jacob6838** [comment]
> > > Looks good, but do we want to add in some unit tests to cover changes? Actually it looks like we don't have any unit tests for most or all of the intersection side of things. Did you want to tackle all the tests at once in another PR or add in some tests to cover these changes now?
> > 
> > 
> > The tests for the intersection components are going to be quite substantial... even for some of the smaller tests, there is a lot of setup to mock the state stores, which will be mostly shared between the tests. I would rather tackle these in large groups (probably not al at once, but certainly batched)
> 
> So for now we're ok with the changed code not having any tests and pushing that to a backlog item?

Actually, I could see utility of adding some tests here. Some of this code is pretty tangled up... Only issue is I don't think it would be done before the new year

**Comment by payneBrandon** [comment]
> > > > Looks good, but do we want to add in some unit tests to cover changes? Actually it looks like we don't have any unit tests for most or all of the intersection side of things. Did you want to tackle all the tests at once in another PR or add in some tests to cover these changes now?
> > > 
> > > 
> > > The tests for the intersection components are going to be quite substantial... even for some of the smaller tests, there is a lot of setup to mock the state stores, which will be mostly shared between the tests. I would rather tackle these in large groups (probably not al at once, but certainly batched)
> > 
> > 
> > So for now we're ok with the changed code not having any tests and pushing that to a backlog item?
> 
> Actually, I could see utility of adding some tests here. Some of this code is pretty tangled up... Only issue is I don't think it would be done before the new year

I've added in a few feature backlog item (280590) to handle adding in unit tests going forward. I'll get this one approved and merged in, but we'll want to work on getting those unit tests in ASAP starting next sprint

**Review by payneBrandon — APPROVED** [review]
Changes look good, unit tests will need to be brought up to speed as mentioned in comment but this will be a separate PR

**Pull request merged**
