### PR TITLE
Firmware Manager Upgrade Queue

### PR DESCRIPTION
**Pull request by drewjj**
# PR Details

## Description

Adds a queue to the firmware manager that only allows 20 RSUs to be actively upgrading concurrently. This is a configurable value with a new environment variable. Any RSUs wanting to be upgraded beyond this limit will wait on a new queue that will be pulled from when new upgrades start and when they end.

The documentation, sample ENV, and K8s scripts have been updated.

## How Has This Been Tested?

Local unit tests and CDOT GCP K8s environment.

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [x] My changes require new environment variables:
  - [x] I have updated the docker-compose, K8s YAML, and all dependent deployment configuration files.
- [x] My changes require updates to the documentation:
  - [x] I have updated the documentation accordingly.
- [x] My changes require updates and/or additions to the unit tests:
  - [x] I have modified/added tests to cover my changes.
- [x] All existing tests pass.

### CODE REVIEW

**Review by mwodahl — COMMENTED** [review]
The code looks great! I did run into the following issue when running pytest in the services directory, however. Is this something that you're seeing as well?
f"Adding '{rsu["ipv4_address"]}' to the firmware manager upgrade queue"
                     ^^^^^^^^^^^^
SyntaxError: f-string: unmatched '['

**Comment by drewjj** [comment]
> The code looks great! I did run into the following issue when running pytest in the services directory, however. Is this something that you're seeing as well? f"Adding '{rsu["ipv4_address"]}' to the firmware manager upgrade queue" ^^^^^^^^^^^^ SyntaxError: f-string: unmatched '['

Weird, I do not get this. And to think of it, the CICD steps all pass on GitHub too which makes me think it isn't just a plain syntax issue. Not sure how a syntax issue would be occurring for only you though.

**Comment by mwodahl** [comment]
> The code looks great! I did run into the following issue when running pytest in the services directory, however. Is this something that you're seeing as well? f"Adding '{rsu["ipv4_address"]}' to the firmware manager upgrade queue" ^^^^^^^^^^^^ SyntaxError: f-string: unmatched '['

This was happening because testing was incorrectly run with python3.11 - these tests all passed when run in the python3.12 virtual environment

**Review by mwodahl — APPROVED** [review]

**Review by payneBrandon — APPROVED** [review]
lgtm!

**Pull request merged**
