### PR TITLE
Further Security Measures

### PR DESCRIPTION
**Pull request by mwodahl**
Includes the following updates:
- Updates user role to pull from SecureLocalStorage instead of state when displaying admin components
- Removed npm vulnerabilities that were fixable
- Updated unit tests to pass with code changes

Note: running npm audit does still show 8 vulnerabilties (6 high, 2 moderate). This is due to the use of the react-scripts package which we require to run npm start, npm build, and npm test. Unfortunately, this package does not have much recent activity and these vulnerabilities have been present for a while. It is likely worth our time to consider swapping this package out in the future.

### CODE REVIEW

**Review by dmccoystephenson — CHANGES_REQUESTED** [review]
I'm experiencing some failing unit tests when running `npm run test` in the 'webapp' directory:

image

**Review by drewjj — COMMENTED** [review]
I am going to wait on this one for until the typescript pr gets merged just in case this requires a mild amount of rework.

**Comment by drewjj** [comment]
Lets get this updated with what is on develop now. We will need to combine your changes with the new Typescript files properly. No remaining JS files should exist. The Typescript files are named the exact same as their corresponding older JS files so this should be pretty straightforward.

**Review by dmccoystephenson — APPROVED** [review]
After updating npm to v10.2.4, the unit tests for the webapp are passing. This looks good to me!

**Review by drewjj — APPROVED** [review]
Looks good and tests well.

**Pull request merged**
