### PR TITLE
Python Formatting

### PR DESCRIPTION
**Pull request by Michael7371**
Updates include:

- Installed the black pip package: "pip install black"
- Updated existing formatting with the following command in the project root: "black ."
- Added the commit to a .git-blame-ignore-revs to preserve git blame history.
- Added the black vscode extension to the vscode extensions.json file
- Set the default python formatter to black in settings.json, also set it to format on save.

The default formatting looked good to me, but I also am not too picky on this type of thing. Let me know what you all think.

### CODE REVIEW

**Review by drewjj — APPROVED** [review]
Seems fine with me. I just code with whatever I have in front of me lol.

**Comment by drewjj** [comment]
Need to address some merge conflicts now.

**Comment by Michael7371** [comment]
> Need to address some merge conflicts now.

Should be all good now!

**Comment by drewjj** [comment]
Lol more merge conflicts. I guess we should fix them. Until this pr gets 2 approvals before something else does this may keep happening.

**Review by drewjj — APPROVED** [review]
Refreshing my approval on this one.

**Review by jacob6838 — APPROVED** [review]
Sorry, forgot this was waiting on me! Got this running on my machine, looks great

**Pull request merged**
