### PR TITLE
Add docker-compose file for webapp deployment

### PR DESCRIPTION
**Pull request by mwodahl**
Adds docker-compose-webapp-deployment.yml to be used when building the webapp image for deployment. This fixes a cv-manager bug where the counts dropdown menu does not display any message options.

### CODE REVIEW

**Review by drewjj — APPROVED** [review]
This looks good

**Review by dmccoystephenson — CHANGES_REQUESTED** [review]
Would you please update the documentation to clarify that the COUNTS_MSG_TYPES & DOT_NAME environment variables must be set at docker build time for the web app to work? It also wouldn't hurt to put the purpose of the 'docker-compose-webapp-deployment.yml' file at the top of the file in a comment.

**Comment by mwodahl** [comment]
> Would you please update the documentation to clarify that the COUNTS_MSG_TYPES & DOT_NAME environment variables must be set at docker build time for the web app to work? It also wouldn't hurt to put the purpose of the 'docker-compose-webapp-deployment.yml' file at the top of the file in a comment.

Added additional comments in sample.env and at the top of the docker-compose-webapp-deployment-yml file to state its purpose and ensure that a user sets the COUNTS_MSG_TYPES & DOT_NAME environment variables before building an image for deployment

**Review by dmccoystephenson — APPROVED** [review]
Looks good to me!

**Pull request merged**
